from sqlalchemy import Column, Integer, String, Date, DateTime, ForeignKey, Text, func
from sqlalchemy.orm import relationship

from app.database import Base


class Report(Base):
    """Lab report model."""

    __tablename__ = "reports"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    uploaded_at = Column(DateTime, server_default=func.now(), nullable=False)
    report_date = Column(Date, nullable=False)
    source = Column(String(20), nullable=False)  # "file" or "manual"
    notes = Column(Text, nullable=True)
    file_path = Column(String(500), nullable=True)
    summary_text = Column(Text, nullable=True)  # Generated by ML pipeline

    # Relationships
    user = relationship("User", back_populates="reports")
    lab_values = relationship("LabValue", back_populates="report", cascade="all, delete-orphan")

    def __repr__(self):
        return f"<Report(id={self.id}, date={self.report_date}, source={self.source})>"
